Gg 29 verify that the entered email or username and password match a record in the database
4Chat-Newton/4chat pull request #16
Opened 2023-01-27 11:30 UTC by qoentz

Error management for the register form, connected back and frontend for register user. 
Lifted cors restrictions., added host-variable in server.ts.

2023-01-27 11:51 UTC, samwiseGhandi commented on src/components/Register.tsx
> +                //TODO needs to be implemented with the login functionality
tänk på att detta ska bort innan vi merge:ar in i main

2023-01-27 11:52 UTC, samwiseGhandi commented on src/components/Register.tsx
> +                  // }
tänk på att detta ska bort innan main

2023-01-27 11:53 UTC, samwiseGhandi commented on src/useFetch.tsx
> +import { useState, useEffect } from 'react';
varför finns denna filen

2023-01-27 11:54 UTC, samwiseGhandi requested changes
Bra jobbat, fattar dock inte syftet just nu med att merge:a in en fil som är tom "useFetch.tsx"

2023-01-27 11:54 UTC, samwiseGhandi commented on src/useFetch.tsx
> +import { useState, useEffect } from 'react';
let me know

2023-01-27 11:56 UTC, M0ller commented on src/components/Register.tsx
> +                  // }
den ska implementeras så fort login funkar. 👍

2023-01-27 12:01 UTC, M0ller commented on src/useFetch.tsx
> +import { useState, useEffect } from 'react';
det var för att vi felsökte fetch url till backend. Just nu måste vi skriva fetch('http://localhost:8080/data/register') för att nå den. Normalt sätt ska man bara behöva skriva fetch('/data/register'). Vi får kolla upp det senare. Tror det är kopplat till useFetch eller Proxy.

2023-01-27 12:01 UTC, M0ller commented on src/useFetch.tsx
> +import { useState, useEffect } from 'react';
+ Bortagen just nu.

2023-01-27 12:05 UTC, M0ller reviewed
I have reviewed the PR

2023-01-30 08:20 UTC, M0ller reviewed
fast review

2023-01-30 08:27 UTC, samwiseGhandi commented
Nani, vad är det som behövs reviewas?

2023-01-30 09:01 UTC, M0ller commented
> Nani, vad är det som behövs reviewas?

Ska bara granskas och mergas in. Sen får vi skicka en "deployment mail" till benjamin när vi kör det till main. Vi kan kolla om vi kan sätta en github action som automatiskt skickar ett mail till honom när en merge görs till main. Det hade varit fett.

2023-01-30 09:36 UTC, merged