Gg 98 create UI for chatrooms
4Chat-Newton/4chat pull request #23
Opened 2023-02-02 09:54 UTC by barkatrahimi

2023-02-02 10:02 UTC, barkatrahimi reviewed
jag och simon har reviewat den

2023-02-03 10:37 UTC, Liha86 approved these changes

2023-02-03 12:00 UTC, M0ller reviewed
looks ok

2023-02-03 12:06 UTC, samwiseGhandi requested changes

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/Chat.tsx
> +    </div>
Detta hade kunnat vara en egen komponent

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/Chat.tsx
> +        </div>
Detta hade också kunnat vara en egen komponent

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/ChatRouter.tsx
> +        <Route path="/terms" element={<Terms />} />
används terms?

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/Inbox.tsx
> +          <button className="rooms">Rooms</button>
likadant här, har själva datan som ska finnas inuti i egna komponenter

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/Navbar.tsx
> +        </header>
stabil komponent! (Y)

2023-02-03 12:06 UTC, samwiseGhandi commented on src/components/style.css
> +    background: #303030;
lägg in alla färger i variablar så att dem är enklare att nå i alla css filer, och även bätre practise att dela upp css fil per komponent.

2023-02-03 12:06 UTC, samwiseGhandi commented on src/pages/ChatRoom.tsx
> +    <Chat/>
Bra

2023-02-03 15:46 UTC, samwiseGhandi approved these changes

2023-02-03 15:46 UTC, samwiseGhandi commented on src/components/style.css
> +    --red: #ee2829;
najs

2023-02-03 15:46 UTC, samwiseGhandi commented on src/components/RightComponent/Inbox.tsx
> +          <button className="rooms">Rooms</button>
Detta kommer också behövas extraheras när vi har dem klara

2023-02-06 09:08 UTC, M0ller approved these changes
Looks ok

2023-02-06 09:20 UTC, merged